# 1. Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:



In [4]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [26]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')


Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


# 2. Дан оператор поворота на 180 градусов, задаваемый матрицей. Показать, что любой вектор является для него собственным.
Покажите, что любой вектор считается для него собственным.

# Собственный вектор оператора A — это такой ненулевой вектор, действие оператора на который сводится к умножению его на число: Ax=λx.

In [17]:
a = np.array([[-1, 0], [0, -1]])

In [18]:
print(f'Матрица A:\n{a}')

Матрица A:
[[-1  0]
 [ 0 -1]]


# 3. Пусть линейный оператор задан матрицей. Установить, является ли вектор x=(1,1) собственным вектором этого линейного оператора.

In [27]:
A = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'\nlambda = {w[1]}, x1 = {round(v[0, 1] / v[1,1], 2)} * x2')
print(f'lambda = {w[0]}, x1 = {round(v[0, 0] / v[1,0], 2)} * x2')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]

lambda = 1.9999999789265757, x1 = 1.0 * x2
lambda = 2.0000000210734243, x1 = 1.0 * x2


# 4. Пусть линейный оператор задан матрицей. Установить, является ли вектор x=(3, -3, -4) собственным вектором этого линейного оператора.

In [31]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')


Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
