In [1]:
import numpy as np

1. Установите, какие произведения матриц 𝐴𝐵 и 𝐵𝐴

определены, и найдите размерности полученных матриц:

а) 𝐴
— матрица 4×2, 𝐵 — матрица 4×2

б) 𝐴
— матрица 2×5, 𝐵 — матрица 5×3

в) 𝐴
— матрица 8×3, 𝐵 — матрица 3×8

г) 𝐴
— квадратная матрица 4×4, 𝐵 — квадратная матрица 4×4.

Если количество столбцов в первой матрице соответствует количеству строк во второй, то можно сказать, что произведение матриц определено. 

а) произведение матриц неопределено, 2 не равно 4; 

б) произведение матриц определено, 5 = 5, размерность полученной матрицы 2×3; 

в) произведение матриц определено, 3 = 3, размерность полученной матрицыь 8×8; 

г) произведение матриц определено, 4 = 4, размерность полученной матрицы 4×4.

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [3]:
a = np.array([[1, -2], [3, 0]])
print(f'Матрица:\n{a}')

b = np.array([[4, -1], [0, 5]])
print(f'Матрица:\n{b}')

Матрица:
[[ 1 -2]
 [ 3  0]]
Матрица:
[[ 4 -1]
 [ 0  5]]


In [4]:
print(f'Матрица С = A + B\n{a + b}')

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


In [5]:
print(f'Матрица AB\n{np.dot(a, b)}')

Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [7]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица:\n{A}')
print(f'Матрица:\n{B}')
print(f'Матрица:\n{C}')

print(f'Комбинация 3𝐴−2𝐵+4𝐶\n{3*A -2*B + 4*C}')

Матрица:
[[ 1  7]
 [ 3 -6]]
Матрица:
[[ 0  5]
 [ 2 -1]]
Матрица:
[[ 2 -4]
 [ 1  1]]
Комбинация 3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

In [11]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A}')

print(f'Транспонированная матрица:\n{A.T}')
print(f'Матрица 𝐴𝐴𝑇:\n{np.dot(A, A.T)}')
print(f'Матрица 𝐴𝑇𝐴:\n{np.dot(A.T, A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица 𝐴𝐴𝑇:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица 𝐴𝑇𝐴:
[[45  0]
 [ 0 14]]


### Part 2

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [14]:
a = np.array([[np.sin(0), -np.cos(0)], [np.cos(0), np.sin(0)]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 0. -1.]
 [ 1.  0.]]
Определитель:
1


In [15]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [16]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{c}')
print(f'Определитель:\n{np.linalg.det(c):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) Согласно свойству для двух квадратных матриц одинакового размера, $$det(AB)=detA\cdot detB.$$
$$det(AA) = detA\cdot detA = 16$$

б) Определитель транспонированной матрицы равен определителю исходной:

$$detA^{T}=detA = 4$$

в) Умножение строки или столбца матрицы на число $\lambda$ приведёт к умножению определителя матрицы на то же число. 

- Доказательство этого свойства элементарно, так как, исходя из формулы определителя, множитель из указанной строки будет в каждом из слагаемых при нахождении определителя разложением по этой строке/столбцу, что равнозначно его умножению на это число.
 
$$det(2A)= detA * 2^n = 16$$

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [17]:
d = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{d}')
print(f'Определитель:\n{np.linalg.det(d):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


Матрица называется сингулярной или вырожденной, если её определитель равен нулю

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [18]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [19]:
x1 = [0, 0, 2, 1]
y1 = [0, 0, 2, 2]
z1 = [0, 0, 4, 3]
d = [2, 3, 5, 6]

b = np.array([x1, y1, z1, d])
r1 = np.linalg.matrix_rank(b)

print(f'Ранг матрицы: {r1}')

Ранг матрицы: 3
