## Практическое задание №1

__1.__ Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__2.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


__3.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__4.__ Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

### №1

In [1]:
import numpy as np

In [2]:
def gauss_method(A, b, n):
    rnk_A = np.linalg.matrix_rank(A)
    rnk_Ab = np.linalg.matrix_rank(np.hstack((A, b)))
    if  rnk_A == rnk_Ab == n:
        return 'Cистема имеет единственное решение'
    elif (rnk_A == rnk_Ab) and (rnk_A < n):
        return 'Cистема имеет бесконечное количество решений'
    elif rnk_A < rnk_Ab:
        return 'Cистема несовместна'

In [3]:
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
b = np.array([0, -2, 4]).reshape(-1, 1)
gauss_method(A, b, 4)

'Cистема имеет бесконечное количество решений'

### №2

In [5]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, 17, 0]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема имеет единственное решение'

In [6]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема несовместна'

In [7]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема имеет бесконечное количество решений'

### №3

In [8]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1]).reshape(-1, 1)
gauss_method(A, b, 4)

'Cистема имеет единственное решение'

## Практическое задание №2

__1.__ Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__2*.__ Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    
__3*.__ Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4*.__ Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__5*.__ Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

### №1

In [14]:
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7]).reshape(-1, 1)

x1 = np.linalg.det(np.hstack((b, A[:,1].reshape(-1, 1)))) /  np.linalg.det(A)
x1

4.999999999999998

In [15]:
x2 = np.linalg.det(np.hstack((A[:,0].reshape(-1, 1), b))) /  np.linalg.det(A)
x2

1.9999999999999996

In [16]:
np.linalg.solve(A, b)

array([[5.],
       [2.]])

In [17]:
A = np.array([[2, -1, 5], [1, 2, -3], [2, 4, 1]])
b = np.array([10, -2, 1]).reshape(-1, 1)

In [18]:
x_1 = np.linalg.det(np.hstack((b, A[:,1:]))) /  np.linalg.det(A)
x_1

2.6000000000000023

In [19]:
x_2 = np.linalg.det(np.hstack((A[:,:1], b, A[:,-1:]))) /  np.linalg.det(A)
x_2

-1.2285714285714293

In [20]:
x_3 = np.linalg.det(np.hstack((A[:,:2], b))) /  np.linalg.det(A)
x_3

0.7142857142857143

In [21]:
np.linalg.solve(A, b)

array([[ 2.6       ],
       [-1.22857143],
       [ 0.71428571]])

### №2`

In [26]:
import pprint
import scipy
import scipy.linalg

A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = scipy.linalg.lu(A)
print("A:")
pprint.pprint(A)

print("P (permutation):")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])
P (permutation):
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.8       , 1.        ]])
U:
array([[ 3.        , 26.        , 30.        ],
       [ 0.        , -8.33333333, -8.        ],
       [ 0.        ,  0.        ,  0.4       ]])


In [27]:
B = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
P, L, U = scipy.linalg.lu(B)
print("B:")
pprint.pprint(B)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

B:
array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])
P:
array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])
L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.75      , -0.25      ,  1.        ,  0.        ],
       [ 0.25      ,  0.75      , -0.17073171,  1.        ]])
U:
array([[  4.        ,  22.        ,  53.        ,  33.        ],
       [  0.        ,  -6.        , -18.5       ,  -7.5       ],
       [  0.        ,   0.        , -15.375     ,  -8.625     ],
       [  0.        ,   0.        ,   0.        ,  -0.09756098]])


### №3

In [28]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
P, L, U = scipy.linalg.lu(A)
print("A:")
pprint.pprint(A)

print("P (permutation):")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])
P (permutation):
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])
L:
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.81818182,  1.        ,  0.        ],
       [ 0.18181818, -0.12      ,  1.        ]])
U:
array([[11.        ,  7.        ,  5.        ],
       [ 0.        ,  2.27272727, -0.09090909],
       [ 0.        ,  0.        ,  2.08      ]])


In [29]:
y1 = 1
y2 = -6 - 0.82
y3 = -5 -0.18 +0.12*y2
print(f'y1: {y1:.1f}, y2: {y2:.1f}, y3: {y3:.1f}')

y1: 1.0, y2: -6.8, y3: -6.0


In [30]:
x3 = y3/2.08
x2 = (y2 + 0.09 * x3)/ 2.27
x1 = (y1- 5*x3 - 7*x2)/11
print(f'x1: {x1:.1f}, x2: {x2:.1f}, x3: {x3:.1f}')

x1: 3.4, x2: -3.1, x3: -2.9
